//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 03:01:38 PM CEST 
//


package isbn._1_931666_33_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:isbn:1-931666-33-4}existDates" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{urn:isbn:1-931666-33-4}places"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}place"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}localDescription"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}localDescriptions"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}legalStatus"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}legalStatuses"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}function"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}functions"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}languageUsed"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}languagesUsed"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}occupation"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}occupations"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}mandate"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}mandates"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}structureOrGenealogy"/>
 *           &lt;element ref="{urn:isbn:1-931666-33-4}generalContext"/>
 *         &lt;/choice>
 *         &lt;element ref="{urn:isbn:1-931666-33-4}biogHist" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}id"/>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "existDates",
    "placesOrPlaceOrLocalDescription",
    "biogHist"
})
@XmlRootElement(name = "description")
public class Description {

    protected ExistDates existDates;
    @XmlElements({
        @XmlElement(name = "places", type = Places.class),
        @XmlElement(name = "place", type = Place.class),
        @XmlElement(name = "localDescription", type = LocalDescription.class),
        @XmlElement(name = "localDescriptions", type = LocalDescriptions.class),
        @XmlElement(name = "legalStatus", type = LegalStatus.class),
        @XmlElement(name = "legalStatuses", type = LegalStatuses.class),
        @XmlElement(name = "function", type = Function.class),
        @XmlElement(name = "functions", type = Functions.class),
        @XmlElement(name = "languageUsed", type = LanguageUsed.class),
        @XmlElement(name = "languagesUsed", type = LanguagesUsed.class),
        @XmlElement(name = "occupation", type = Occupation.class),
        @XmlElement(name = "occupations", type = Occupations.class),
        @XmlElement(name = "mandate", type = Mandate.class),
        @XmlElement(name = "mandates", type = Mandates.class),
        @XmlElement(name = "structureOrGenealogy", type = StructureOrGenealogy.class),
        @XmlElement(name = "generalContext", type = GeneralContext.class)
    })
    protected List<Object> placesOrPlaceOrLocalDescription;
    protected List<BiogHist> biogHist;
    @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;

    /**
     * Gets the value of the existDates property.
     * 
     * @return
     *     possible object is
     *     {@link ExistDates }
     *     
     */
    public ExistDates getExistDates() {
        return existDates;
    }

    /**
     * Sets the value of the existDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExistDates }
     *     
     */
    public void setExistDates(ExistDates value) {
        this.existDates = value;
    }

    /**
     * Gets the value of the placesOrPlaceOrLocalDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the placesOrPlaceOrLocalDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlacesOrPlaceOrLocalDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Places }
     * {@link Place }
     * {@link LocalDescription }
     * {@link LocalDescriptions }
     * {@link LegalStatus }
     * {@link LegalStatuses }
     * {@link Function }
     * {@link Functions }
     * {@link LanguageUsed }
     * {@link LanguagesUsed }
     * {@link Occupation }
     * {@link Occupations }
     * {@link Mandate }
     * {@link Mandates }
     * {@link StructureOrGenealogy }
     * {@link GeneralContext }
     * 
     * 
     */
    public List<Object> getPlacesOrPlaceOrLocalDescription() {
        if (placesOrPlaceOrLocalDescription == null) {
            placesOrPlaceOrLocalDescription = new ArrayList<Object>();
        }
        return this.placesOrPlaceOrLocalDescription;
    }

    /**
     * Gets the value of the biogHist property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the biogHist property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBiogHist().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BiogHist }
     * 
     * 
     */
    public List<BiogHist> getBiogHist() {
        if (biogHist == null) {
            biogHist = new ArrayList<BiogHist>();
        }
        return this.biogHist;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

}
