//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 02:54:19 PM CEST 
//


package isbn._1_931666_22_9;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for c02 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="c02">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="head" type="{urn:isbn:1-931666-22-9}head" minOccurs="0"/>
 *         &lt;element name="did" type="{urn:isbn:1-931666-22-9}did"/>
 *         &lt;group ref="{urn:isbn:1-931666-22-9}m.desc.full" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="thead" type="{urn:isbn:1-931666-22-9}thead" minOccurs="0"/>
 *           &lt;element name="c03" type="{urn:isbn:1-931666-22-9}c03" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:isbn:1-931666-22-9}a.desc.c"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "c02", propOrder = {
    "head",
    "did",
    "mDescFull",
    "theadAndC03"
})
public class C02 {

    protected Head head;
    @XmlElement(required = true)
    protected Did did;
    @XmlElements({
        @XmlElement(name = "accessrestrict", type = Accessrestrict.class),
        @XmlElement(name = "accruals", type = Accruals.class),
        @XmlElement(name = "acqinfo", type = Acqinfo.class),
        @XmlElement(name = "altformavail", type = Altformavail.class),
        @XmlElement(name = "appraisal", type = Appraisal.class),
        @XmlElement(name = "arrangement", type = Arrangement.class),
        @XmlElement(name = "bibliography", type = Bibliography.class),
        @XmlElement(name = "bioghist", type = Bioghist.class),
        @XmlElement(name = "controlaccess", type = Controlaccess.class),
        @XmlElement(name = "custodhist", type = Custodhist.class),
        @XmlElement(name = "descgrp", type = Descgrp.class),
        @XmlElement(name = "fileplan", type = Fileplan.class),
        @XmlElement(name = "index", type = Index.class),
        @XmlElement(name = "odd", type = Odd.class),
        @XmlElement(name = "originalsloc", type = Originalsloc.class),
        @XmlElement(name = "otherfindaid", type = Otherfindaid.class),
        @XmlElement(name = "phystech", type = Phystech.class),
        @XmlElement(name = "prefercite", type = Prefercite.class),
        @XmlElement(name = "processinfo", type = Processinfo.class),
        @XmlElement(name = "relatedmaterial", type = Relatedmaterial.class),
        @XmlElement(name = "scopecontent", type = Scopecontent.class),
        @XmlElement(name = "separatedmaterial", type = Separatedmaterial.class),
        @XmlElement(name = "userestrict", type = Userestrict.class),
        @XmlElement(name = "dsc", type = Dsc.class),
        @XmlElement(name = "dao", type = Dao.class),
        @XmlElement(name = "daogrp", type = Daogrp.class),
        @XmlElement(name = "note", type = Note.class)
    })
    protected List<Object> mDescFull;
    @XmlElements({
        @XmlElement(name = "thead", type = Thead.class),
        @XmlElement(name = "c03", type = C03 .class)
    })
    protected List<Object> theadAndC03;
    @XmlAttribute(name = "level")
    protected AvLevel level;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "altrender")
    @XmlSchemaType(name = "anySimpleType")
    protected String altrender;
    @XmlAttribute(name = "audience")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String audience;
    @XmlAttribute(name = "otherlevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String otherlevel;
    @XmlAttribute(name = "encodinganalog")
    @XmlSchemaType(name = "anySimpleType")
    protected String encodinganalog;
    @XmlAttribute(name = "tpattern")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String tpattern;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link Head }
     *     
     */
    public Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head }
     *     
     */
    public void setHead(Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the did property.
     * 
     * @return
     *     possible object is
     *     {@link Did }
     *     
     */
    public Did getDid() {
        return did;
    }

    /**
     * Sets the value of the did property.
     * 
     * @param value
     *     allowed object is
     *     {@link Did }
     *     
     */
    public void setDid(Did value) {
        this.did = value;
    }

    /**
     * Gets the value of the mDescFull property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mDescFull property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMDescFull().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Accessrestrict }
     * {@link Accruals }
     * {@link Acqinfo }
     * {@link Altformavail }
     * {@link Appraisal }
     * {@link Arrangement }
     * {@link Bibliography }
     * {@link Bioghist }
     * {@link Controlaccess }
     * {@link Custodhist }
     * {@link Descgrp }
     * {@link Fileplan }
     * {@link Index }
     * {@link Odd }
     * {@link Originalsloc }
     * {@link Otherfindaid }
     * {@link Phystech }
     * {@link Prefercite }
     * {@link Processinfo }
     * {@link Relatedmaterial }
     * {@link Scopecontent }
     * {@link Separatedmaterial }
     * {@link Userestrict }
     * {@link Dsc }
     * {@link Dao }
     * {@link Daogrp }
     * {@link Note }
     * 
     * 
     */
    public List<Object> getMDescFull() {
        if (mDescFull == null) {
            mDescFull = new ArrayList<Object>();
        }
        return this.mDescFull;
    }

    /**
     * Gets the value of the theadAndC03 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theadAndC03 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheadAndC03().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Thead }
     * {@link C03 }
     * 
     * 
     */
    public List<Object> getTheadAndC03() {
        if (theadAndC03 == null) {
            theadAndC03 = new ArrayList<Object>();
        }
        return this.theadAndC03;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link AvLevel }
     *     
     */
    public AvLevel getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvLevel }
     *     
     */
    public void setLevel(AvLevel value) {
        this.level = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the altrender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltrender() {
        return altrender;
    }

    /**
     * Sets the value of the altrender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltrender(String value) {
        this.altrender = value;
    }

    /**
     * Gets the value of the audience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudience() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudience(String value) {
        this.audience = value;
    }

    /**
     * Gets the value of the otherlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherlevel() {
        return otherlevel;
    }

    /**
     * Sets the value of the otherlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherlevel(String value) {
        this.otherlevel = value;
    }

    /**
     * Gets the value of the encodinganalog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncodinganalog() {
        return encodinganalog;
    }

    /**
     * Sets the value of the encodinganalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncodinganalog(String value) {
        this.encodinganalog = value;
    }

    /**
     * Gets the value of the tpattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpattern() {
        return tpattern;
    }

    /**
     * Sets the value of the tpattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpattern(String value) {
        this.tpattern = value;
    }

}
