//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.25 at 07:25:38 AM CEST 
//


package it.mibac.san.ead_san;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://san.mibac.it/ead-san/}did"/>
 *         &lt;element name="processinfo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="non indicato"/>
 *               &lt;enumeration value="scheda pubblicata"/>
 *               &lt;enumeration value="scheda in via di compilazione"/>
 *               &lt;enumeration value="pubblicazione locale/interna"/>
 *               &lt;enumeration value="scheda di prova"/>
 *               &lt;enumeration value="scheda in via di pubblicazione"/>
 *               &lt;enumeration value="da rivedere"/>
 *               &lt;enumeration value="rivista"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://san.mibac.it/ead-san/}relatedmaterial"/>
 *         &lt;element ref="{http://san.mibac.it/ead-san/}otherfindaid" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="level" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="otherlevel" />
 *       &lt;attribute name="otherlevel" use="required" type="{http://san.mibac.it/ead-san/}stringNotEmpty" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "did",
    "processinfo",
    "relatedmaterial",
    "otherfindaid"
})
@XmlRootElement(name = "archdesc")
public class Archdesc {

    @XmlElement(required = true)
    protected Did did;
    @XmlElement(required = true)
    protected String processinfo;
    @XmlElement(required = true)
    protected Relatedmaterial relatedmaterial;
    protected List<Otherfindaid> otherfindaid;
    @XmlAttribute(name = "level", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String level;
    @XmlAttribute(name = "otherlevel", required = true)
    protected String otherlevel;

    /**
     * Gets the value of the did property.
     * 
     * @return
     *     possible object is
     *     {@link Did }
     *     
     */
    public Did getDid() {
        return did;
    }

    /**
     * Sets the value of the did property.
     * 
     * @param value
     *     allowed object is
     *     {@link Did }
     *     
     */
    public void setDid(Did value) {
        this.did = value;
    }

    /**
     * Gets the value of the processinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessinfo() {
        return processinfo;
    }

    /**
     * Sets the value of the processinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessinfo(String value) {
        this.processinfo = value;
    }

    /**
     * Gets the value of the relatedmaterial property.
     * 
     * @return
     *     possible object is
     *     {@link Relatedmaterial }
     *     
     */
    public Relatedmaterial getRelatedmaterial() {
        return relatedmaterial;
    }

    /**
     * Sets the value of the relatedmaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Relatedmaterial }
     *     
     */
    public void setRelatedmaterial(Relatedmaterial value) {
        this.relatedmaterial = value;
    }

    /**
     * Gets the value of the otherfindaid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherfindaid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherfindaid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Otherfindaid }
     * 
     * 
     */
    public List<Otherfindaid> getOtherfindaid() {
        if (otherfindaid == null) {
            otherfindaid = new ArrayList<Otherfindaid>();
        }
        return this.otherfindaid;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        if (level == null) {
            return "otherlevel";
        } else {
            return level;
        }
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the otherlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherlevel() {
        return otherlevel;
    }

    /**
     * Sets the value of the otherlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherlevel(String value) {
        this.otherlevel = value;
    }

}
