//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.25 at 07:25:38 AM CEST 
//


package it.mibac.san.ead_san;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://san.mibac.it/ead-san/}unitid"/>
 *         &lt;element ref="{http://san.mibac.it/ead-san/}unittitle" maxOccurs="unbounded"/>
 *         &lt;element name="unitdate" type="{http://san.mibac.it/ead-san/}datetype" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://san.mibac.it/ead-san/}physdesc"/>
 *         &lt;element ref="{http://san.mibac.it/ead-san/}abstract" minOccurs="0"/>
 *         &lt;element name="origination" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://san.mibac.it/ead-san/}repository" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unitid",
    "unittitle",
    "unitdate",
    "physdesc",
    "_abstract",
    "origination",
    "repository"
})
@XmlRootElement(name = "did")
public class Did {

    @XmlElement(required = true)
    protected Unitid unitid;
    @XmlElement(required = true)
    protected List<Unittitle> unittitle;
    @XmlElement(required = true)
    protected List<Datetype> unitdate;
    @XmlElement(required = true)
    protected Physdesc physdesc;
    @XmlElement(name = "abstract")
    protected Abstract _abstract;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected List<String> origination;
    @XmlElement(required = true)
    protected List<Repository> repository;

    /**
     * Gets the value of the unitid property.
     * 
     * @return
     *     possible object is
     *     {@link Unitid }
     *     
     */
    public Unitid getUnitid() {
        return unitid;
    }

    /**
     * Sets the value of the unitid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unitid }
     *     
     */
    public void setUnitid(Unitid value) {
        this.unitid = value;
    }

    /**
     * Gets the value of the unittitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unittitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnittitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Unittitle }
     * 
     * 
     */
    public List<Unittitle> getUnittitle() {
        if (unittitle == null) {
            unittitle = new ArrayList<Unittitle>();
        }
        return this.unittitle;
    }

    /**
     * Gets the value of the unitdate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unitdate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnitdate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Datetype }
     * 
     * 
     */
    public List<Datetype> getUnitdate() {
        if (unitdate == null) {
            unitdate = new ArrayList<Datetype>();
        }
        return this.unitdate;
    }

    /**
     * Gets the value of the physdesc property.
     * 
     * @return
     *     possible object is
     *     {@link Physdesc }
     *     
     */
    public Physdesc getPhysdesc() {
        return physdesc;
    }

    /**
     * Sets the value of the physdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Physdesc }
     *     
     */
    public void setPhysdesc(Physdesc value) {
        this.physdesc = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Abstract }
     *     
     */
    public Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abstract }
     *     
     */
    public void setAbstract(Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the origination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the origination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrigination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOrigination() {
        if (origination == null) {
            origination = new ArrayList<String>();
        }
        return this.origination;
    }

    /**
     * Gets the value of the repository property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repository property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepository().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Repository }
     * 
     * 
     */
    public List<Repository> getRepository() {
        if (repository == null) {
            repository = new ArrayList<Repository>();
        }
        return this.repository;
    }

}
