//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.25 at 07:25:38 AM CEST 
//


package it.mibac.san.eac_san;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://san.mibac.it/eac-san/}otherRecordId"/>
 *         &lt;element ref="{http://san.mibac.it/eac-san/}maintenanceStatus"/>
 *         &lt;element ref="{http://san.mibac.it/eac-san/}sources"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "otherRecordId",
    "maintenanceStatus",
    "sources"
})
@XmlRootElement(name = "control")
public class Control {

    @XmlElement(required = true)
    protected OtherRecordId otherRecordId;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maintenanceStatus;
    @XmlElement(required = true)
    protected Sources sources;

    /**
     * Gets the value of the otherRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link OtherRecordId }
     *     
     */
    public OtherRecordId getOtherRecordId() {
        return otherRecordId;
    }

    /**
     * Sets the value of the otherRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherRecordId }
     *     
     */
    public void setOtherRecordId(OtherRecordId value) {
        this.otherRecordId = value;
    }

    /**
     * Gets the value of the maintenanceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaintenanceStatus() {
        return maintenanceStatus;
    }

    /**
     * Sets the value of the maintenanceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaintenanceStatus(String value) {
        this.maintenanceStatus = value;
    }

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link Sources }
     *     
     */
    public Sources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sources }
     *     
     */
    public void setSources(Sources value) {
        this.sources = value;
    }

}
