//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.25 at 07:25:38 AM CEST 
//


package it.mibac.san.eac_san;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://san.mibac.it/eac-san/}control"/>
 *         &lt;element ref="{http://san.mibac.it/eac-san/}cpfDescription"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "control",
    "cpfDescription"
})
@XmlRootElement(name = "eac-cpf")
public class EacCpf {

    @XmlElement(required = true)
    protected Control control;
    @XmlElement(required = true)
    protected CpfDescription cpfDescription;

    /**
     * Gets the value of the control property.
     * 
     * @return
     *     possible object is
     *     {@link Control }
     *     
     */
    public Control getControl() {
        return control;
    }

    /**
     * Sets the value of the control property.
     * 
     * @param value
     *     allowed object is
     *     {@link Control }
     *     
     */
    public void setControl(Control value) {
        this.control = value;
    }

    /**
     * Gets the value of the cpfDescription property.
     * 
     * @return
     *     possible object is
     *     {@link CpfDescription }
     *     
     */
    public CpfDescription getCpfDescription() {
        return cpfDescription;
    }

    /**
     * Sets the value of the cpfDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link CpfDescription }
     *     
     */
    public void setCpfDescription(CpfDescription value) {
        this.cpfDescription = value;
    }

}
