//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.25 at 07:25:38 AM CEST 
//


package it.mibac.san.eac_san;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.mibac.san.eac_san package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EntityType_QNAME = new QName("http://san.mibac.it/eac-san/", "entityType");
    private final static QName _MaintenanceStatus_QNAME = new QName("http://san.mibac.it/eac-san/", "maintenanceStatus");
    private final static QName _RelationEntry_QNAME = new QName("http://san.mibac.it/eac-san/", "relationEntry");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.mibac.san.eac_san
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NameEntryParallel }
     * 
     */
    public NameEntryParallel createNameEntryParallel() {
        return new NameEntryParallel();
    }

    /**
     * Create an instance of {@link DateSet }
     * 
     */
    public DateSet createDateSet() {
        return new DateSet();
    }

    /**
     * Create an instance of {@link EacCpf }
     * 
     */
    public EacCpf createEacCpf() {
        return new EacCpf();
    }

    /**
     * Create an instance of {@link Control }
     * 
     */
    public Control createControl() {
        return new Control();
    }

    /**
     * Create an instance of {@link OtherRecordId }
     * 
     */
    public OtherRecordId createOtherRecordId() {
        return new OtherRecordId();
    }

    /**
     * Create an instance of {@link Sources }
     * 
     */
    public Sources createSources() {
        return new Sources();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link CpfDescription }
     * 
     */
    public CpfDescription createCpfDescription() {
        return new CpfDescription();
    }

    /**
     * Create an instance of {@link Identity }
     * 
     */
    public Identity createIdentity() {
        return new Identity();
    }

    /**
     * Create an instance of {@link it.mibac.san.eac_san.NameEntry }
     * 
     */
    public it.mibac.san.eac_san.NameEntry createNameEntry() {
        return new it.mibac.san.eac_san.NameEntry();
    }

    /**
     * Create an instance of {@link NameEntryParallel.NameEntry }
     * 
     */
    public NameEntryParallel.NameEntry createNameEntryParallelNameEntry() {
        return new NameEntryParallel.NameEntry();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link ExistDates }
     * 
     */
    public ExistDates createExistDates() {
        return new ExistDates();
    }

    /**
     * Create an instance of {@link DateSet.Date }
     * 
     */
    public DateSet.Date createDateSetDate() {
        return new DateSet.Date();
    }

    /**
     * Create an instance of {@link PlaceDates }
     * 
     */
    public PlaceDates createPlaceDates() {
        return new PlaceDates();
    }

    /**
     * Create an instance of {@link PlaceDate }
     * 
     */
    public PlaceDate createPlaceDate() {
        return new PlaceDate();
    }

    /**
     * Create an instance of {@link DescriptiveEntries }
     * 
     */
    public DescriptiveEntries createDescriptiveEntries() {
        return new DescriptiveEntries();
    }

    /**
     * Create an instance of {@link DescriptiveEntry }
     * 
     */
    public DescriptiveEntry createDescriptiveEntry() {
        return new DescriptiveEntry();
    }

    /**
     * Create an instance of {@link BiogHist }
     * 
     */
    public BiogHist createBiogHist() {
        return new BiogHist();
    }

    /**
     * Create an instance of {@link Relations }
     * 
     */
    public Relations createRelations() {
        return new Relations();
    }

    /**
     * Create an instance of {@link ResourceRelation }
     * 
     */
    public ResourceRelation createResourceRelation() {
        return new ResourceRelation();
    }

    /**
     * Create an instance of {@link CpfRelation }
     * 
     */
    public CpfRelation createCpfRelation() {
        return new CpfRelation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://san.mibac.it/eac-san/", name = "entityType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEntityType(String value) {
        return new JAXBElement<String>(_EntityType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://san.mibac.it/eac-san/", name = "maintenanceStatus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMaintenanceStatus(String value) {
        return new JAXBElement<String>(_MaintenanceStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://san.mibac.it/eac-san/", name = "relationEntry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRelationEntry(String value) {
        return new JAXBElement<String>(_RelationEntry_QNAME, String.class, null, value);
    }

}
