//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.25 at 07:25:38 AM CEST 
//


package it.mibac.san.ricerca_san;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://san.mibac.it/ricerca-san/}titlestmt"/>
 *         &lt;element ref="{http://san.mibac.it/ricerca-san/}publicationstmt"/>
 *         &lt;element ref="{http://san.mibac.it/ricerca-san/}notestmt" minOccurs="0"/>
 *         &lt;element ref="{http://san.mibac.it/ricerca-san/}editionstmt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titlestmt",
    "publicationstmt",
    "notestmt",
    "editionstmt"
})
@XmlRootElement(name = "filedesc")
public class Filedesc {

    @XmlElement(required = true)
    protected Titlestmt titlestmt;
    @XmlElement(required = true)
    protected Publicationstmt publicationstmt;
    protected Notestmt notestmt;
    protected Editionstmt editionstmt;

    /**
     * Gets the value of the titlestmt property.
     * 
     * @return
     *     possible object is
     *     {@link Titlestmt }
     *     
     */
    public Titlestmt getTitlestmt() {
        return titlestmt;
    }

    /**
     * Sets the value of the titlestmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Titlestmt }
     *     
     */
    public void setTitlestmt(Titlestmt value) {
        this.titlestmt = value;
    }

    /**
     * Gets the value of the publicationstmt property.
     * 
     * @return
     *     possible object is
     *     {@link Publicationstmt }
     *     
     */
    public Publicationstmt getPublicationstmt() {
        return publicationstmt;
    }

    /**
     * Sets the value of the publicationstmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publicationstmt }
     *     
     */
    public void setPublicationstmt(Publicationstmt value) {
        this.publicationstmt = value;
    }

    /**
     * Gets the value of the notestmt property.
     * 
     * @return
     *     possible object is
     *     {@link Notestmt }
     *     
     */
    public Notestmt getNotestmt() {
        return notestmt;
    }

    /**
     * Sets the value of the notestmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notestmt }
     *     
     */
    public void setNotestmt(Notestmt value) {
        this.notestmt = value;
    }

    /**
     * Gets the value of the editionstmt property.
     * 
     * @return
     *     possible object is
     *     {@link Editionstmt }
     *     
     */
    public Editionstmt getEditionstmt() {
        return editionstmt;
    }

    /**
     * Sets the value of the editionstmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Editionstmt }
     *     
     */
    public void setEditionstmt(Editionstmt value) {
        this.editionstmt = value;
    }

}
