//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.25 at 07:25:38 AM CEST 
//


package it.mibac.san.ricerca_san;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.mibac.san.ricerca_san package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.mibac.san.ricerca_san
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Edition }
     * 
     */
    public Edition createEdition() {
        return new Edition();
    }

    /**
     * Create an instance of {@link Extptr }
     * 
     */
    public Extptr createExtptr() {
        return new Extptr();
    }

    /**
     * Create an instance of {@link Archdesc }
     * 
     */
    public Archdesc createArchdesc() {
        return new Archdesc();
    }

    /**
     * Create an instance of {@link Did }
     * 
     */
    public Did createDid() {
        return new Did();
    }

    /**
     * Create an instance of {@link Eadheader }
     * 
     */
    public Eadheader createEadheader() {
        return new Eadheader();
    }

    /**
     * Create an instance of {@link Eadid }
     * 
     */
    public Eadid createEadid() {
        return new Eadid();
    }

    /**
     * Create an instance of {@link Filedesc }
     * 
     */
    public Filedesc createFiledesc() {
        return new Filedesc();
    }

    /**
     * Create an instance of {@link Titlestmt }
     * 
     */
    public Titlestmt createTitlestmt() {
        return new Titlestmt();
    }

    /**
     * Create an instance of {@link Publicationstmt }
     * 
     */
    public Publicationstmt createPublicationstmt() {
        return new Publicationstmt();
    }

    /**
     * Create an instance of {@link Notestmt }
     * 
     */
    public Notestmt createNotestmt() {
        return new Notestmt();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Editionstmt }
     * 
     */
    public Editionstmt createEditionstmt() {
        return new Editionstmt();
    }

    /**
     * Create an instance of {@link Ead }
     * 
     */
    public Ead createEad() {
        return new Ead();
    }

}
