//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.25 at 07:25:38 AM CEST 
//


package it.mibac.san.cat_import;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import it.mibac.san.eac_san.EacCpf;
import it.mibac.san.scons_san.Scons;


/**
 * <p>Java class for catRecordBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="catRecordBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://san.mibac.it/ead-san/}ead"/>
 *         &lt;element ref="{http://san.mibac.it/ricerca-san/}ead"/>
 *         &lt;element ref="{http://san.mibac.it/eac-san/}eac-cpf"/>
 *         &lt;element ref="{http://san.mibac.it/scons-san/}scons"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "catRecordBody", propOrder = {
    "content"
})
public class CatRecordBody {

    @XmlElementRefs({
        @XmlElementRef(name = "eac-cpf", namespace = "http://san.mibac.it/eac-san/", type = EacCpf.class, required = false),
        @XmlElementRef(name = "scons", namespace = "http://san.mibac.it/scons-san/", type = Scons.class, required = false),
        @XmlElementRef(name = "ead", namespace = "http://san.mibac.it/ead-san/", type = it.mibac.san.ead_san.Ead.class, required = false),
        @XmlElementRef(name = "ead", namespace = "http://san.mibac.it/ricerca-san/", type = it.mibac.san.ricerca_san.Ead.class, required = false)
    })
    protected List<Object> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Ead" is used by two different parts of a schema. See: 
     * line 82 of file:/Users/massi/Desktop/Lavoro/Sorgenti/Teca2015/Teca2015ExportSan/tecaExport/tecaSchemaSan/xsd/cat-import.xsd
     * line 81 of file:/Users/massi/Desktop/Lavoro/Sorgenti/Teca2015/Teca2015ExportSan/tecaExport/tecaSchemaSan/xsd/cat-import.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link it.mibac.san.ricerca_san.Ead }
     * {@link EacCpf }
     * {@link Scons }
     * {@link it.mibac.san.ead_san.Ead }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
